---
- name: Load distro variables
  ansible.builtin.include_vars: '{{ ansible_distribution | lower }}.yaml'

- name: Execute distro-specific tasks
  ansible.builtin.include_tasks: '{{ ansible_distribution | lower }}.yaml'

- name: Prepare system for rootless containers
  ansible.builtin.include_tasks: rootless.yaml
  when: container_rootless|bool

- name: Manage containers
  ansible.builtin.include_tasks: '{{ container_engine }}.yaml'
...
