---
- name: Run preflight checks
  hosts: monitors,dbservers,ha
  gather_facts: false
  pre_tasks:
    - name: Gather hardware information
      ansible.builtin.setup:
        gather_subset:
          - min
          - network
          - hardware
      tags:
        - always

  roles:
    - role: preflight
      tags:
        - always
...
